### ISSUE TITLE
Why @app.route for fastapi 

### ISSUE THREAD

**Issue by richardokonicha** [authlib/demo-oauth-client#13]

**Comment by ZhengRui** [comment]
I am having the same question. I am implementing a basic social signin using authlib this weekend with fastapi. 

So if I use `@r.get` and then send a fetch request from nextjs client (routed to fastapi through nginx), then the request will fail due to CORS issue, see the discussion at the end of this [issue](https://github.com/tiangolo/fastapi/issues/12). Only when I route to the fastapi backend route by browser (in nextjs use router.push('fastapi_oauth_route')), instead of sending a http request to the fastapi backend route, will I be able to successfully do google authentication, however this way I have to hack a way to so frontend can receive the jwt from fastapi after authentication.

`@r.get` or `@r.route` both works so long as I route through browser rather than sending requests.

**Comment by lepture** [comment]
It was `@app.route` in early versions, because it is using Starlette. I've just updated the code.
